name: Scraper Quotidien (Maroc)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r ScrappingMaroc/requirements.txt

    - name: Lancement du script de scraping
      env:
        MONGO2_URI: ${{ secrets.MONGO2_URI }}
      run: python ScrappingMaroc/Scrapping.py